base_url = "https://ilya-meignan--masson.me"
title = "Ilya Meignan--Masson's webpage"
description = "My personal webpage."

default_language = "en"
generate_feed = true
minify_html = true

[markdown]
  highlight_code = true
  highlight_theme = "visual-studio-dark"
  external_links_target_blank = true
  external_links_no_follow = true
  external_links_no_referrer = true
  smart_punctuation = true

[extra]
  d3_nav = [
    { name = "Home", path = "/" },
    { name = "CV", path = "/cv/" },
    { name = "Research", path = "/research/" },
  ]
  d3_icon = "static/icon.png"
  d3_twitter = "Iliouchka"
  d3_author = "Ilya Meignan--Masson"
